# Generated by Django 5.2.2 on 2025-06-08 02:34

import django.db.models.deletion
import podcast.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "script",
                    models.FileField(
                        upload_to=podcast.models.podcast_script_upload_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                (
                    "audio_file",
                    models.FileField(
                        upload_to=podcast.models.audio_segment_upload_path
                    ),
                ),
                ("start_time", models.PositiveIntegerField(default=0)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_segments",
                        to="podcast.podcast",
                    ),
                ),
            ],
        ),
    ]
