# Generated by Django 5.2.2 on 2025-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="script",
            field=models.TextField(),
        ),
    ]
