# Generated by Django 5.2.2 on 2025-06-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_alter_podcast_script"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiosegment",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="audiosegment",
            name="start_time",
        ),
    ]
