# Generated by Django 5.2.2 on 2025-06-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_remove_audiosegment_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegment",
            name="path",
            field=models.TextField(max_length=200),
        ),
    ]
