# Generated by Django 5.2.2 on 2025-06-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0004_alter_audiosegment_path"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AudioSegment",
            new_name="Segment",
        ),
    ]
