# Generated by Django 5.2.2 on 2025-06-08 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
        ("podcast", "0006_questionresponse_questionresponsesegment"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="podcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="podcast.podcast",
            ),
        ),
        migrations.DeleteModel(
            name="StudySession",
        ),
    ]
